### PR TITLE
Updated script to support helm v3 and modern cert-manager

### PR DESCRIPTION
**Pull request by kha7iq**
This PR is for issue https://github.com/hoeghh/rancher-launcher-kvm/issues/4
The script for rancher has been update to use helm 3 and latest version of cert manger.
Thank you

### CODE REVIEW

**Comment by hoeghh** [comment]
Hi @kha7iq 

Thank you so much for the PR.

I just tested it locally and it works. It does give me a single error but the Rancher does run.

Do you want to investigate, or should i just merge?

```
kubectl get nodes
NAME              STATUS   ROLES                      AGE   VERSION
192.168.122.111   Ready    controlplane,etcd,worker   15d   v1.17.17
 hoeghh  ~  Development  rancher-launcher-kvm  scripts  ./install_rancher_server.sh 192.168.122.111

Adding helm repo for cert-manger & Rancher

"rancher-latest" has been added to your repositories
"jetstack" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ask" chart repository
...Successfully got an update from the "praqma" chart repository
...Successfully got an update from the "rook-release" chart repository
...Successfully got an update from the "jetstack" chart repository
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
	failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
...Successfully got an update from the "rancher-latest" chart repository
...Successfully got an update from the "gitlab" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
 Creating namespace 

namespace/cert-manager created
namespace/cattle-system created
 Installing Cert Manger

NAME: cert-manager
LAST DEPLOYED: Sat Feb 27 12:15:54 2021
NAMESPACE: cert-manager
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
cert-manager has been deployed successfully!

In order to begin issuing certificates, you will need to set up a ClusterIssuer
or Issuer resource (for example, by creating a 'letsencrypt-staging' issuer).

More information on the different types of issuers and how to configure them
can be found in our documentation:

https://cert-manager.io/docs/configuration/

For information on how to configure cert-manager to automatically provision
Certificates for Ingress resources, take a look at the `ingress-shim`
documentation:

https://cert-manager.io/docs/usage/ingress/
 Checking Rollout Status

Waiting for deployment "cert-manager" rollout to finish: 0 of 1 updated replicas are available...
deployment "cert-manager" successfully rolled out
Installing Rancher 

Error: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s: dial tcp 10.43.244.129:443: connect: connection refused

Getting Deployment Status

Waiting for deployment "rancher" rollout to finish: 0 of 3 updated replicas are available...
Waiting for deployment "rancher" rollout to finish: 1 of 3 updated replicas are available...
Waiting for deployment "rancher" rollout to finish: 2 of 3 updated replicas are available...
deployment "rancher" successfully rolled out

NAME      READY   UP-TO-DATE   AVAILABLE   AGE
rancher   3/3     3            3           2m16s
 hoeghh  ~  Development  rancher-launcher-kvm  scripts  kubectl get ingress -A
NAMESPACE       NAME         HOSTS                            ADDRESS           PORTS     AGE
cattle-system   rancher      rancher-192.168.122.111.nip.io   192.168.122.111   80, 443   2m31s
ingress-nginx   prometheus   prometheus.example.com           192.168.122.111   80        15d
```

```
NAMESPACE                 NAME                                      READY   STATUS      RESTARTS   AGE
cattle-system             helm-operation-4fdw5                      0/2     Completed   0          3m26s
cattle-system             helm-operation-8vf8k                      0/2     Completed   0          2m53s
cattle-system             helm-operation-p66hm                      0/2     Completed   0          3m40s
cattle-system             helm-operation-q4q5t                      0/2     Completed   0          3m18s
cattle-system             helm-operation-vl7lf                      0/2     Completed   0          4m17s
cattle-system             rancher-7d7fcc7ccd-56wqx                  1/1     Running     0          6m9s
cattle-system             rancher-7d7fcc7ccd-pbqzk                  1/1     Running     0          6m9s
cattle-system             rancher-7d7fcc7ccd-zkhnf                  1/1     Running     0          6m9s
cattle-system             rancher-webhook-5c6fcb875-z428f           1/1     Running     0          3m37s
cert-manager              cert-manager-747d74fdd-xxfxh              1/1     Running     0          6m28s
cert-manager              cert-manager-cainjector-ddb7c7889-q2xc4   1/1     Running     0          6m28s
cert-manager              cert-manager-webhook-9bfcf5d74-qrzgl      1/1     Running     0          6m28s
fleet-system              fleet-agent-76445df948-scbjq              1/1     Running     0          117s
fleet-system              fleet-controller-568dc5cdf4-4x69f         1/1     Running     0          3m14s
fleet-system              gitjob-5bbbbbc6fb-lwgw2                   1/1     Running     0          3m14s
ingress-nginx             default-http-backend-67cf578fc4-qxnbn     1/1     Running     3          15d
ingress-nginx             grafana-84cf577bc5-bgsp4                  1/1     Running     3          15d
ingress-nginx             nginx-ingress-controller-rlcjp            1/1     Running     3          15d
ingress-nginx             prometheus-server-85c6c58475-p48qf        1/1     Running     3          15d
kube-system               coredns-7c5566588d-5b2ps                  1/1     Running     3          15d
kube-system               coredns-autoscaler-65bfc8d47d-f2962       1/1     Running     3          15d
kube-system               kube-flannel-q4dhd                        2/2     Running     6          15d
kube-system               metrics-server-6b55c64f86-dbpnj           1/1     Running     3          15d
kube-system               rke-coredns-addon-deploy-job-28fqs        0/1     Completed   0          15d
kube-system               rke-ingress-controller-deploy-job-xqdw4   0/1     Completed   0          15d
kube-system               rke-metrics-addon-deploy-job-mrbgr        0/1     Completed   0          15d
kube-system               rke-network-plugin-deploy-job-zkzhc       0/1     Completed   0          15d
rancher-operator-system   rancher-operator-57f5cd9bc4-5nt7p         1/1     Running     0          3m51s
```

rancher_ui

**Comment by hoeghh** [comment]
This is maybe causing this error

```
kubectl get app -A
NAMESPACE                 NAME                   CHART                  VERSION                                                                  RELEASE NAME           RELEASE VERSION   STATUS
cattle-system             rancher                rancher                2.5.5                                                                    rancher                1                 failed
```

Log output : [rancher-error.txt](https://github.com/hoeghh/rancher-launcher-kvm/files/6054323/rancher-error.txt)

**Comment by kha7iq** [comment]
Hello @hoeghh 
I think it maybe be related to cert-manger deployment, may need to increase the sleep time after the installation  cert-manager.
I will check and update

**Comment by hoeghh** [comment]
@kha7iq I updated the wait to 10 seconds, and then it all worked. I guess it depends on the hardware and resources given to the workernodes. But it would be ok to just set it to 10sec, and commit. Then ill merge :)

And again, thank you so much for the pr.

**Comment by kha7iq** [comment]
I have increased the timer to 20 seconds just to be on the safe side.

**Pull request merged**
